# Generated by Django 6.0.6 on 2026-06-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='train_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='train_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
