# Generated by Django 6.0.6 on 2026-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0002_seat_arrival_time_seat_train_name_seat_train_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat_available_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='is_available',
            new_name='seat_available',
        ),
        migrations.AddField(
            model_name='seat',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='distination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
