# Generated by Django 6.0.6 on 2026-06-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0003_rename_seat_available_date_seat_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('date', 'train_number', 'seat_number')},
        ),
    ]
