# Generated by Django 6.0.6 on 2026-06-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminUser.seat'),
        ),
        migrations.DeleteModel(
            name='Admin_User',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
